mariadb:
  image: linuxserver/mariadb
  environment:
    PUID: "${DUID}"
    PGID: "${DGID}"
    MYSQL_ROOT_PASSWORD: testpassword
    MYSQL_DATABASE: app
    MYSQL_USER: user
    MYSQL_PASSWORD: testpassword
  volumes:
  - ./mysql:/config
web:
  build: .
  user: "${DUID}:${DGID}"
  command: npm run development
  dockerfile: Dockerfile.local
  environment:
    PORT: 5757
    ENV: development
    APP_URL: 'http://localhost:5757'
    MYSQL_HOST: mariadb
    MYSQL_PORT: 3306
    MYSQL_USER: user
    MYSQL_PASSWORD: testpassword
    MYSQL_DB: app
  links:
    - mariadb
  ports:
    - "5757:5757"
  volumes:
    - .:/app
    - /app/node_modules
